### ISSUE TITLE
No common busybox build?

### ISSUE THREAD

**Issue by 01micko** [puppylinux-woof-CE/petbuilds#28]
I see there is no common busybox petbuild. I need an armhf version with all the new applets - in particular `guess_fstype`.

**Comment by woodenshoe-wi** [comment]
I think the busybox petbuild is kept in the initrd_progs repo because it is used in the initrd.

https://github.com/puppylinux-woof-CE/initrd_progs/tree/master/pkg/busybox_static

It looks like it was updated two days ago, so I think it is the current version.

**Comment by 01micko** [comment]
Thanks @woodenshoe-wi , that should suffice for my needs.

**Comment by wdlkmpx** [comment]
I create a pet package when i'm ready to release a new initrd-progs tarball

Here is the the latest busybox for the main sfs:
http://distro.ibiblio.org/puppylinux/arm/pet_packages-armv6/busybox-1.30.1-arm_musl_static.pet
http://distro.ibiblio.org/puppylinux/pet_packages-common32/busybox-1.30.1-x86_musl_static.pet
http://distro.ibiblio.org/puppylinux/pet_packages-common64/busybox-1.30.1-x86_64_musl_static.pet

http://www.01micko.com/wdlkmpx/woof-CE/busybox-1.30.1-aarch64_musl_static.pet

Yesterday i introduced an incompatibility, the new busybox dc is no longer patched
https://github.com/puppylinux-woof-CE/initrd_progs/commit/34c9d52a347e0d80acf84762564a18888f5d6ae9

That requires a global patch in rootfs-skeleton and the initrd.. patch already available locally.

Since i don't know how to create a .deb/.txz/.rpm/etc package, my idea was to create a new tarball, simplify the initrd and make both build systems use the woof-arch tarball.. but i'm being slow.

Also add woof-arch-gui tarball with a predefined set of apps that must be there.

I kind of grew tired of constantly having to edit the pkgs_specs of all compat distro versions, so my plan was to enforce my will in some other way..
